/*
 * action types
 */

export const SignupActions = {
  SET_EMAIL: 'SIGNUP_SET_EMAIL',
  SET_EMAIL_FORM_STATUS: 'SIGNUP_SET_EMAIL_FORM_STATUS',
  SET_PASSWORD: 'SIGNUP_SET_PASSWORD',
  SET_PASSWORD_FORM_STATUS: 'SIGNUP_SET_PASSWORD_FORM_STATUS',
  SET_CONFIRM_PASSWORD: 'SIGNUP_SET_CONFIRM_PASSWORD',
  SET_CONFIRM_PASSWORD_FORM_STATUS: 'SIGNUP_SET_CONFIRM_PASSWORD_FORM_STATUS',
  SET_FORM_STATUS: 'SIGNUP_SET_FORM_STATUS',
  INIT_ERROR_MODAL: 'SIGNUP_INIT_ERROR_MODAL_OPEN',
  SET_SHOW: 'SIGNUP_SET_SHOW'
}
