/*
 * action types
 */

export const SignupActions = {
  SET_EMAIL_FORM_STATUS: 'SIGNUP_SET_EMAIL_FORM_STATUS',
  SET_PASSWORD_FORM_STATUS: 'SIGNUP_SET_PASSWORD_FORM_STATUS',
  SET_CONFIRM_PASSWORD_FORM_STATUS: 'SIGNUP_SET_CONFIRM_PASSWORD_FORM_STATUS',
}
