/*
 * action types
 */

export const ConfirmActions = {
  SET_EMAIL_FORM_STATUS: 'CONFIRM_SET_EMAIL_FORM_STATUS',
  SET_CONFIRMATION_CODE_FORM_STATUS: 'CONFIRM_SET_CONFIRMATION_CODE_FORM_STATUS',
  SET_FORM_STATUS: 'CONFIRM_SET_FORM_STATUS',
  INIT_ERROR_MODAL: 'CONFIRM_INIT_ERROR_MODAL_OPEN',
  SET_SHOW: 'CONFIRM_SET_SHOW'
}
