/*
 * action types
 */
 
export const AwsConfirmActions = {
	CONFIRM_REQUEST: 'AWS_CONFIRM_REQUEST',
	CONFIRM_SUCCESS: 'AWS_CONFIRM_SUCCESS',
	CONFIRM_FAILURE: 'AWS_CONFIRM_FAILURE',
	RESEND_REQUEST: 'AWS_RESEND_REQUEST',
	RESEND_SUCCESS: 'AWS_RESEND_SUCCESS',
	RESEND_FAILURE: 'AWS_RESEND_FAILURE'

};

