/*
 * action types
 */

export const SignupActions = {
  SET_FIRSTNAME_FORM_STATUS: 'SIGNUP_SET_FIRSTNAME_FORM_STATUS',
  SET_LASTNAME_FORM_STATUS: 'SIGNUP_SET_LASTNAME_FORM_STATUS',
  SET_USERNAME_FORM_STATUS: 'SIGNUP_SET_USERNAME_FORM_STATUS',
  SET_PHONENUMBER_FORM_STATUS: 'SIGNUP_SET_PHONENUMBER_FORM_STATUS',
  SET_EMAIL_FORM_STATUS: 'SIGNUP_SET_EMAIL_FORM_STATUS',
  SET_PASSWORD_FORM_STATUS: 'SIGNUP_SET_PASSWORD_FORM_STATUS',
  SET_CONFIRM_PASSWORD_FORM_STATUS: 'SIGNUP_SET_CONFIRM_PASSWORD_FORM_STATUS',
  SET_MFA_FORM_STATUS: 'SIGNUP_SET_MFA_FORM_STATUS'
};
