/*
 * action types
 */


export const GetACodeActions = {
  SET_USERNAME: 'GETACODE_SET_USERNAME',
  SET_USERNAME_FORM_STATUS: 'GETACODE_SET_USERNAME_FORM_STATUS',
  SET_PASSWORD: 'GETACODE_SET_PASSWORD',
  SET_PASSWORD_FORM_STATUS: 'GETACODE_SET_PASSWORD_FORM_STATUS',
  SET_FORM_STATUS: 'GETACODE_SET_FORM_STATUS'
}
