/*
 * action types
 */


export const LoginActions = {
  SET_EMAIL: 'SET_EMAIL',
  SET_EMAIL_FORM_STATUS: 'SET_EMAIL_FORM_STATUS',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_PASSWORD_FORM_STATUS: 'SET_PASSWORD_FORM_STATUS',
  SET_FORM_STATUS: 'SET_FORM_STATUS',
  INIT_ERROR_MODAL: 'INIT_ERROR_MODAL_OPEN',
  SET_SHOW: 'SET_SHOW'
}
