/*
 * action types
 */


export const LoginActions = {
  SET_EMAIL: 'LOGIN_SET_EMAIL',
  SET_EMAIL_FORM_STATUS: 'LOGIN_SET_EMAIL_FORM_STATUS',
  SET_PASSWORD: 'LOGIN_SET_PASSWORD',
  SET_PASSWORD_FORM_STATUS: 'LOGIN_SET_PASSWORD_FORM_STATUS',
  SET_FORM_STATUS: 'LOGIN_SET_FORM_STATUS'
}
